FROM rocm/pytorch:rocm6.3_ubuntu22.04_py3.10_pytorch_release_2.4.0

# Set build arguments
ARG ROCM_VERSION=6.3.0
ARG GPU_ARCH

# Environment configuration
ENV ROCM_PATH=/opt/rocm-${ROCM_VERSION}
ENV PATH=${ROCM_PATH}/bin:${ROCM_PATH}/llvm/bin:${PATH}
ENV LD_LIBRARY_PATH=${ROCM_PATH}/lib:${LD_LIBRARY_PATH}
#ENV PYTORCH_ROCM_ARCH=${GPU_ARCH:-gfx942:gfx1100}
# ENV HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-9.4.2}

# # Install system dependencies
# RUN apt-get update && \
#     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
#     git cmake gcc-12 g++-12 libnuma-dev libjansson-dev \
#     libncurses6 libnl-3-200 libnl-route-3-200 libpython3.12-dev \
#     hipblaslt-dev rccl-dev libopenmpi-dev openmpi-bin libfabric-dev && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    python3.10 \
    python3.10-dev \
    python3-pip \
    git \
    libsndfile1-dev \
    tesseract-ocr \
    espeak-ng \
    rocthrust-dev \
    hipsparse-dev \
    hipblas-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 && \
    python -m pip install -U pip

RUN pip install -U --no-cache-dir ninja packaging git+https://github.com/facebookresearch/detectron2.git pytesseract "itsdangerous<2.1.0"

#RUN rm -rf /opt/bitsandbytes ; \
#    mkdir /opt/bitsandbytes ; \
#    git clone -b rocm_enabled_multi_backend --recursive https://github.com/ROCm/bitsandbytes /opt/bitsandbytes ; \
#    cd /opt/bitsandbytes ; \
#    pip install -r requirements-dev.txt ; \
#    cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx1100" -DAMDGPU_TARGETS="gfx1100" -S . ; \
#    nice make -j ; \
#    python3 -m pip wheel --no-deps . --wheel-dir=/opt/wheels ; \
#    pip install /opt/wheels/bitsandbytes-*.whl


RUN pip3 install \
    transformers==4.47.0 \
    accelerate==1.2.0 \
    optimum-amd==0.1.0 \
    sentencepiece==0.2.0 \
    ninja==1.11.1.3 \
    scipy==1.13.0 \
    datasets \
    huggingface-hub>=0.24.0 \
    safetensors>=0.4.1 \
    peft \
    trl \
    numpy \
    pandas \
    matplotlib \
    seaborn \
    tensorboard \
    wheel \
    pytest \
    evaluate \
    tokenizers \
    huggingface-hub \
    einops \
    wandb \
    plotext

RUN ln -s /opt/rocm-6.3.0 /opt/rocm-6.3.2

RUN git clone https://github.com/ROCm/flash-attention.git flash-attention-v2 && \
    cd flash-attention-v2 && \
    git checkout 2554f490101742ccdc56620a938f847f61754be6 && \
    git submodule update --init --recursive && \
    GPU_ARCHS="native" PYTORCH_ROCM_ARCH="gfx940;gfx942" python setup.py install && \
    cd .. && \
    rm -rf flash-attention-v2

RUN rm -rf /opt/bitsandbytes ; \
    mkdir /opt/bitsandbytes ; \
    git clone -b rocm_enabled_multi_backend --recursive https://github.com/ROCm/bitsandbytes /opt/bitsandbytes ; \
    cd /opt/bitsandbytes ; \
    pip install -r requirements-dev.txt ; \
    cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx1100" -DAMDGPU_TARGETS="gfx1100" -S . ; \
    nice make -j ; \
    python3 -m pip wheel --no-deps . --wheel-dir=/opt/wheels ; \
    pip install /opt/wheels/bitsandbytes-*.whl

WORKDIR /workspace
